### ISSUE TITLE
Show ISC options for post featured image block

### ISSUE THREAD

**Issue by webzunft** [image-source-control/image-source-control#125]
Show the ISC options for an image also for the "post featured image" block when editing posts.

Current solution
---

Users can go to the image settings to edit the source, but not do this directly in the block editor.

Expected behavior
---

Same as for the image block.

![Bildschirmfoto 2021-09-13 um 11 40 07](https://user-images.githubusercontent.com/2728720/133061544-913d6901-3eab-4b36-94d1-b4569344343b.png)

Priority
---

Low. No one else asked about this and users have a way to edit the source.

**Comment by Galanos** [comment]
Sidebar ISC field support for the Featured Image block was added through PR #181 (issue #137).
