### ISSUE TITLE
Prevent warning in widget editor

### ISSUE THREAD

**Issue by webzunft** [image-source-control/image-source-control#138]
Since WordPress 5.8, an error notices appears under Appearance > Widgets when ISC is installed.

> PHP Notice:  wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets).

It is triggered by https://github.com/image-source-control/image-source-control/blob/865c8662f434a1363848bdd7bea4d412b2fd85f7/includes/gutenberg/gutenberg.php#L87.

Expected behavior
---

Don’t trigger a warning, but if possible, show ISC options for image block also in widgets.

**Comment by cnhk** [comment]
@webzunft The PR https://github.com/image-source-control/image-source-control/pull/139 is ready for review.
