### ISSUE TITLE
Allow to close the Missing Sources message

### ISSUE THREAD

**Issue by webzunft** [image-source-control/image-source-control#165]
The warning about missing image sources does not have a close button.

<img width="1280" alt="Bildschirmfoto 2022-04-25 um 15 36 34" src="https://user-images.githubusercontent.com/2728720/165100159-30039cea-5f67-47f9-b52f-0f3ed2949bbf.png">

Users can close the message by disabling it completely, but they might forget that they opted in and where this option was. We might link to it.

Current solution
---

The message about missing sources is an opt-in feature so it does not show up by default.
Users can close it by disabling the appropriate option in the settings.

Expected behavior
---

Show a link to the option in the message.

Version a: "close" link in the message:

<img width="858" alt="Bildschirmfoto 2022-04-25 um 15 40 08" src="https://user-images.githubusercontent.com/2728720/165100854-c4b297c2-7985-46d5-8f1b-d3427d5af3fb.png">

Version b: close button at the end

<img width="870" alt="Bildschirmfoto 2022-04-25 um 15 42 49" src="https://user-images.githubusercontent.com/2728720/165101301-a40153e2-f23a-40d2-9023-9715366a64c1.png">

I prefer the first, because it is more obvious. The WP close button normally closes a message right away and is expected to not show this message again. But I would not allow disabling all such messages for all users from one user who is annoyed by it with a simple click.

Priority
---

User request

**Comment by webzunft** [comment]
@Galanos what is your take on this?

**Comment by Galanos** [comment]
@webzunft Haven’t had multiple users in mind, but you’re right in pointing it out. I prefer the first version, too, the second one deviates from expected WordPress behavior. But I would name the anchor “disable”:

> See the **missing sources** list or **disable** this warning.
