### ISSUE TITLE
ISC input fields in the block editor are empty

### ISSUE THREAD

**Issue by Galanos** [image-source-control/image-source-control#171]
This is a bug with the ISC block in the current master (**not** live 2.6.0) that turned up after [merging PR 158](https://github.com/image-source-control/image-source-control/pull/158) that seems to be directly related to it.

@cnhk, sorry for not noticing this right away, I’ll add this particular check to my test workflow. @webzunft asked me to open this issue and assign it to you.

How to reproduce
---

1. Install the current master
2. Enter edit mode of any post
3. Select any image that has ISC source info
4. See the empty ISC source fields in the sidebar

Entering source info and updating the post, deselecting and reselecting the image keeps the field filled; but exiting and re-entering the post’s edit mode clears it.

Notice that the source info is still intact; it displays correctly in the frontend and in the media library.

@cnhk Although you may use any you like, I’ll send you the link to the staging site that I used in Slack.

Expected behavior
---

The ISC source fields should stay filled in and should reflect the database state at all times.

Priority
---

This bug blocks the master for any releases so it’s quite urgent.

Additional context
---

There is a second issue—that I noticed in the course of getting to the bottom of this one—that seems **not** to be related to this. I’ll add a separate issue for that.
@cnhk Please see for yourself if there might be a connection.

Tests
---

- [ ] image’s ISC source fields in the block editor’s sidebar display the current state of the data record at all times, even after exiting and re-entering the edit mode of the post
- [ ] Media Library, attachment page, and frontend stay unaffected and work as intended

**Comment by cnhk** [comment]
@Galanos here the [fix](https://github.com/image-source-control/image-source-control/pull/173)
