### ISSUE TITLE
PHP warning on the front end when there is a source but no plugin options yet

### ISSUE THREAD

**Issue by cnhk** [image-source-control/image-source-control#175]
**Describe the bug**

There is a PHP error notice on the front end, when an image has a source but the plugin's option is not set yet.

How to reproduce
---

1. install and activate ISC on a fresh install or alternatively delete ISC option via `phpmyadmin` or a third party plugin
2. do not go to the settings page, do not save the plugin's option.
3. on a page with an image, set a source if the image doesn't have one.
4. visit that page

Expected behavior
---
Should not be a PHP notice at `wp-content/plugins/image-source-control-isc/public/public.php:497`

**Screenshots**

![image](https://user-images.githubusercontent.com/3407174/168078272-fe74134f-7d2c-481d-afa7-aa169f47cc02.png)

Priority
---

Low. People usually go the settings page (if there is one) when playing with a new plugin.

**Comment by webzunft** [comment]
I am not able to reproduce the issue.

https://github.com/image-source-control/image-source-control/blob/96e558f5bd47f2b59f51384f329f9fa325587936/public/public.php#L497 should fall back to the default values and $options should never be empty. Did you test it on a completely new site or could this be an issue that caused the options to be empty on a dev site?

**Comment by cnhk** [comment]
A fresh WP installation

**Comment by cnhk** [comment]
Don't really know how the code ended like that, but in 

`$headline = $this->options['image_list_headline']`, 

the `ISC_Public::$options` attribute is set by calling `get_option( 'isc_options' )` in https://github.com/image-source-control/image-source-control/blob/master/isc.class.php#L104, which don't use a default value 

while just one line above (line 496) there is `$options  = $this->get_isc_options();` which actually use a default value. But that `$options` variable is never used.

**Comment by cnhk** [comment]
There is something I don't understand. Both on the test site (https://test-setup.com/isc-175/) and locally, there are no ISC options, the theme is the same, `WP_DEBUG` is `true` but I don't manage to get the same warning I get locally.

**Comment by Galanos** [comment]
> I don't manage to get the same warning I get locally

@cnhk Maybe differing PHP versions and you’re dealing with a deprecated feature?

**Comment by webzunft** [comment]
@cnhk good catch! Please test if #179 resolves the issue.

**Comment by cnhk** [comment]
> Maybe differing PHP versions and you’re dealing with a deprecated feature?

Yes that's it. The warning is shown only on PHP 7.4+ apparently. The test site is running 7.3.
