### ISSUE TITLE
ISC form elements defocus when Ajax saving call completes in Media Library modal

### ISSUE THREAD

**Issue by Galanos** [image-source-control/image-source-control#197]
In the Media Library modal—both in _Media > Library_ as well as in a post, selecting images from the Media Library modal—, after changing the content of ISC form element “A” (input field, checkbox, dropdown menu) of any image and tabbing or clicking into ISC form element “B” triggers an Ajax call to save the info of form element “A“. Once this call is completed (positive HTTP feedback, I reckon) the presently focussed form element “B” becomes defocussed.
This does _not_ affect ISC Pro’s batch editing of form elements in the Media Library list view. Neither does it affect the WP core input fields “Alternative text”, “Caption”, etc. in the modal.

How to reproduce
---

1. Go either to _Media > Library (grid view)_ or edit a random post and place an image block, enter the Media Library modal
2. Select a random image, put cursor in input field “Image Source”, enter random info
3. Click or (speedily) tab into input field “Image Source URL” and watch it closely
4. After a second or two, depending on your ping and the server’s load, the “Image Source URL” input field becomes defocussed, the cursor is displaced from it

Expected behavior
---

The expected behavior is for the defocussing to seize, for any constellation of the exact form elements “A” and “B”.

Priority
---

Medium. This has been a minor problem for a while, but now, a [first report of annoyance](https://wordpress.org/support/topic/image-source-not-showing-on-picture/#post-15739835) has been submitted.

Additional context
---

I think I remember that this had been a problem for the post-editing mode’s **sidebar** ISC input fields, too, but this seems to be gone after the switch to REST API calls in ISC 2.7.0.

Tests
---

- [ ] forwards tabbing, backwards tabbing and clicking from form element “A” to “B”—for any constellation of the four ISC form elements—does not defocus form element “B” after automatic background saving of “A”

**Comment by Galanos** [comment]
I don’t know if this helps at all but while looking at the XHRs in the Media Library modal I noticed that WordPress’ Heartbeat calls do have an attribute “has_focus” that is “true” when an input field is selected while the Heartbeat is called and “false” when there isn’t.
<img width="556" alt="Bildschirmfoto 2022-06-17 um 09 23 08" src="https://user-images.githubusercontent.com/2743446/174248673-7b7abe30-a2b3-4a5c-9006-c67d219db6f3.png">
<img width="564" alt="Bildschirmfoto 2022-06-17 um 09 25 04" src="https://user-images.githubusercontent.com/2743446/174248684-4fc0cc2e-ed40-4730-9523-0c13ced04539.png">

The saving calls triggered by deselecting a modified core input field (Alt text, for example) don’t have that attribute, though.
<img width="546" alt="Bildschirmfoto 2022-06-17 um 09 25 18" src="https://user-images.githubusercontent.com/2743446/174248702-c82b8bce-5e98-45f8-9467-8e968f948504.png">

**Comment by cnhk** [comment]
This is a core issue. It happens with other field saved with the `attachment_fields_to_save` (the edit filter does nothing). Below a very simplistic example plugin.

https://drive.google.com/file/d/1I64rQwFA2x82c4HKfsvDEn-rztGa5szQ/view?usp=sharing

In other words, to avoid that we have to save the ISC post meta using our own method. But since it's a core problem there is a chance that it will get a fix later (the core developer must be aware of this though), so it might not worth a fix from our end right now (unless there are a lot of other complaints in the near future).

**Comment by webzunft** [comment]
@cnhk good catch!
There is indeed a core issue ticket since 4.7.5, from 5 years ago.
https://core.trac.wordpress.org/ticket/40909

Can we add this by default to ISC or could this potentially break another plugin?

**Comment by webzunft** [comment]
Valid question :)
Any of the approaches from the ticket. Whichever you find could have fewer side effects.

**Comment by cnhk** [comment]
ok
