### ISSUE TITLE
How to get the source_string only? 

### ISSUE THREAD

**Issue by codegrau** [image-source-control/image-source-control#21]
This is how my featured image is displayed. I want to add the $source_string manually __without the p-markup and source-pretext__ to my figcaption (maybe add other markup by myself), but I really don't know, how to get that $source_string for my featured image. 

````
<figure>
 <img ...>
 <figcaption>
   caption text - $imagesourcecontroloutput
 </figcaption>
</figure>
````

Output of isc_thumbnail_source()
````
return '<p class="isc-source-text">' . $options['source_pretext'] . ' ' . $source_string . '</p>';
````

Looking forward to a hint and a little help

**Comment by webzunft** [comment]
@codegrau 
Could you use `isc_image_source($attachment_id = 0)`?
