### ISSUE TITLE
Do not hardcode margin

### ISSUE THREAD

**Issue by Kipperlenny** [image-source-control/image-source-control#32]
Here https://github.com/webgilde/image-source-control/blob/master/public/assets/js/front-js.js#L69

//caption horizontal margin
var tml = 5;

//caption vertical margin
 var tmt = 5;

is some margin hardocded. Please make this editable in Options or remove it.

**Comment by webzunft** [comment]
Thanks for opening this ticket.

While there would not be an option in the backend, I am open to discussing an implementation that is simpler to change if anyone creates a pull request for it.

**Comment by webzunft** [comment]
#113 allows publishers to remove the default markup and add their own.
