### ISSUE TITLE
missing sources lists, link on mediatitle

### ISSUE THREAD

**Issue by staude** [image-source-control/image-source-control#60]
In the list of missing sources ( upload.php?page=isc_missing_sources_page ) the media title is linked to the page 
( /wp-admin/media.php?attachment_id={$ID}&action=edit )  on which an unnecessary button (insert post) is and does not allow me to delete the medium, among other things. It would be better to link to the media editing page from the title
/wp-admin/upload.php?item={$ID}

**Comment by webzunft** [comment]
Thank you, @staude. This should be fixed in the `master` branch already. Would you mind testing it?

**Comment by staude** [comment]
Hello Thomas, I'll be happy to test. 
We have it in use on a site with 4000 articles and 2000 media. So if you want to test other features as well, please contact me.

**Comment by staude** [comment]
Looks like it's not committed yet :)
https://github.com/webgilde/image-source-control/blob/d53105f6c91721a936e107df07b6b2554c0cc6be/admin/templates/sources.php#L27

**Comment by webzunft** [comment]
Sorry, I did in fact fixed another issue and not this one.
I had a closer look at your suggestion. First, I don’t see the "insert post" button or anything else that is irrelevant on that page.
Instead, that page comes with one great advantage: it automatically redirects the user back to the image source overview page ( upload.php?page=isc_missing_sources_page ) when I click on the update button.

The option to remove the image is indeed missing from that page. I personally never missed it when I wanted to edit sources.

Seems like a draw between these options.

About testing: I am changing a few things in how images are discovered in the content and am adding a few debug options. If you have issues with images and sources not being detected then this would be a great time for me to work on that. Please reach out through https://webgilde.com/de/kontakt/ then.

Edit: there seems to be some referrer logic in `upload.php` as well. I will check it out later when I have more time for testing.

**Comment by webzunft** [comment]
@staude did you have a chance to take a look at my reply?

**Comment by staude** [comment]
I'll look at it after my holiday.

**Comment by webzunft** [comment]
@staude is this still relevant?

**Comment by staude** [comment]
@webzunft  Probably no. My project position ended at the end of September, so I am no longer involved in the project where we had the problem.
